//! Embedded CSS for markdown preview HTML output.

/// GitHub-style markdown body styles with light/dark mode support.
pub const MARKDOWN_CSS: &str = r#"
@media (prefers-color-scheme: light) {
  body {
    background-color: #ffffff;
    color: #1f2328;
  }
  .markdown-body {
    color-scheme: light;
    --fg-default: #1f2328;
    --fg-muted: #656d76;
    --border-default: #d0d7de;
    --bg-muted: #f6f8fa;
    --bg-subtle: #eef1f4;
    --accent-fg: #0969da;
    --mark-bg: #fff8c5;
  }
}

@media (prefers-color-scheme: dark) {
  body {
    background-color: #0d1117;
    color: #e6edf3;
  }
  .markdown-body {
    color-scheme: dark;
    --fg-default: #e6edf3;
    --fg-muted: #8b949e;
    --border-default: #30363d;
    --bg-muted: #161b22;
    --bg-subtle: #21262d;
    --accent-fg: #4493f8;
    --mark-bg: #3d2e00;
  }
}

body {
  margin: 0;
  padding: 2rem 1rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial,
    sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
}

.markdown-body {
  box-sizing: border-box;
  max-width: 980px;
  margin: 0 auto;
  padding: 2rem;
  color: var(--fg-default);
  word-wrap: break-word;
}

.markdown-body * {
  box-sizing: border-box;
}

.markdown-body h1,
.markdown-body h2,
.markdown-body h3,
.markdown-body h4,
.markdown-body h5,
.markdown-body h6 {
  margin-top: 1.5rem;
  margin-bottom: 1rem;
  font-weight: 600;
  line-height: 1.25;
}

.markdown-body h1 {
  font-size: 2em;
  padding-bottom: 0.3em;
  border-bottom: 1px solid var(--border-default);
}

.markdown-body h2 {
  font-size: 1.5em;
  padding-bottom: 0.3em;
  border-bottom: 1px solid var(--border-default);
}

.markdown-body h3 { font-size: 1.25em; }
.markdown-body h4 { font-size: 1em; }
.markdown-body h5 { font-size: 0.875em; }
.markdown-body h6 { font-size: 0.85em; color: var(--fg-muted); }

.markdown-body p,
.markdown-body blockquote,
.markdown-body ul,
.markdown-body ol,
.markdown-body dl,
.markdown-body table,
.markdown-body pre {
  margin-top: 0;
  margin-bottom: 1rem;
}

.markdown-body a {
  color: var(--accent-fg);
  text-decoration: none;
}

.markdown-body a:hover {
  text-decoration: underline;
}

.markdown-body strong { font-weight: 600; }

.markdown-body ul,
.markdown-body ol {
  padding-left: 2em;
}

.markdown-body li + li {
  margin-top: 0.25em;
}

.markdown-body li > p {
  margin-bottom: 0;
}

.markdown-body blockquote {
  padding: 0 1em;
  color: var(--fg-muted);
  border-left: 0.25em solid var(--border-default);
}

.markdown-body hr {
  height: 0.25em;
  padding: 0;
  margin: 1.5rem 0;
  background-color: var(--border-default);
  border: 0;
}

.markdown-body table {
  display: block;
  width: 100%;
  overflow: auto;
  border-spacing: 0;
  border-collapse: collapse;
}

.markdown-body table th,
.markdown-body table td {
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--border-default);
}

.markdown-body table tr {
  background-color: transparent;
  border-top: 1px solid var(--border-default);
}

.markdown-body table tr:nth-child(2n) {
  background-color: var(--bg-muted);
}

.markdown-body table th {
  font-weight: 600;
}

.markdown-body img {
  max-width: 100%;
  box-sizing: content-box;
}

.markdown-body code {
  padding: 0.2em 0.4em;
  margin: 0;
  font-size: 85%;
  font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono",
    monospace;
  background-color: var(--bg-muted);
  border-radius: 6px;
}

.markdown-body pre {
  padding: 1rem;
  overflow: auto;
  font-size: 85%;
  line-height: 1.45;
  background-color: var(--bg-muted);
  border-radius: 6px;
}

.markdown-body pre code {
  display: inline;
  max-width: auto;
  padding: 0;
  margin: 0;
  overflow: visible;
  line-height: inherit;
  word-wrap: normal;
  background-color: transparent;
  border: 0;
}

.markdown-body input[type="checkbox"] {
  margin: 0 0.2em 0.25em -1.4em;
  vertical-align: middle;
}

.markdown-body del {
  text-decoration: line-through;
}

.markdown-body mark {
  background-color: var(--mark-bg);
  color: inherit;
}

.mermaid-diagram {
  text-align: center;
  margin: 1.5rem 0;
  overflow-x: auto;
}

.mermaid-diagram svg {
  max-width: 100%;
  height: auto;
}
"#;

/// Syntax highlighting span styles for syntect ClassedHTMLGenerator (base16-ocean.dark).
pub const HIGHLIGHT_CSS: &str = r#"
/*
 * theme "Base16 Ocean Dark" generated by syntect
 */

.code {
 color: #c0c5ce;
 background-color: #2b303b;
}

.variable.parameter.function {
 color: #c0c5ce;
}
.comment, .punctuation.definition.comment {
 color: #65737e;
}
.punctuation.definition.string, .punctuation.definition.variable, .punctuation.definition.string, .punctuation.definition.parameters, .punctuation.definition.string, .punctuation.definition.array {
 color: #c0c5ce;
}
.none {
 color: #c0c5ce;
}
.keyword.operator {
 color: #c0c5ce;
}
.keyword {
 color: #b48ead;
}
.variable, .variable.other.dollar.only.js {
 color: #bf616a;
}
.entity.name.function, .meta.require, .support.function.any-method, .variable.function {
 color: #8fa1b3;
}
.support.class, .entity.name.class, .entity.name.type.class {
 color: #ebcb8b;
}
.meta.class {
 color: #eff1f5;
}
.keyword.other.special-method {
 color: #8fa1b3;
}
.storage {
 color: #b48ead;
}
.support.function {
 color: #96b5b4;
}
.string, .constant.other.symbol, .entity.other.inherited-class {
 color: #a3be8c;
}
.constant.numeric {
 color: #d08770;
}
.constant {
 color: #d08770;
}
.entity.name.tag {
 color: #bf616a;
}
.entity.other.attribute-name {
 color: #d08770;
}
.entity.other.attribute-name.id, .punctuation.definition.entity {
 color: #8fa1b3;
}
.meta.selector {
 color: #b48ead;
}
.markup.heading .punctuation.definition.heading, .entity.name.section {
 color: #8fa1b3;
}
.keyword.other.unit {
 color: #d08770;
}
.markup.bold, .punctuation.definition.bold {
 color: #ebcb8b;
font-weight: bold;
}
.markup.italic, .punctuation.definition.italic {
 color: #b48ead;
font-style: italic;
}
.markup.raw.inline {
 color: #a3be8c;
}
.string.other.link {
 color: #bf616a;
}
.meta.link {
 color: #d08770;
}
.meta.image {
 color: #d08770;
}
.markup.list {
 color: #bf616a;
}
.markup.quote {
 color: #d08770;
}
.meta.separator {
 color: #c0c5ce;
 background-color: #4f5b66;
}
.markup.inserted, .markup.inserted.git_gutter {
 color: #a3be8c;
}
.markup.deleted, .markup.deleted.git_gutter {
 color: #bf616a;
}
.markup.changed, .markup.changed.git_gutter {
 color: #b48ead;
}
.markup.ignored, .markup.ignored.git_gutter {
 color: #4f5b66;
}
.markup.untracked, .markup.untracked.git_gutter {
 color: #4f5b66;
}
.constant.other.color {
 color: #96b5b4;
}
.string.regexp {
 color: #96b5b4;
}
.constant.character.escape {
 color: #96b5b4;
}
.punctuation.section.embedded, .variable.interpolation {
 color: #ab7967;
}
.invalid.illegal {
 color: #2b303b;
 background-color: #bf616a;
}
"#;
